#Copyright 2020 Sreda Software Solutions. All rights reserved.
#The copyright notice above does not evidence any actual or
#intended publication of such source code. The code contains
#Sreda Software Solutions Confidential Proprietary Information.

server:
  port: ${PORT}
  error.whitelabel.enabled: false

spring:
  application:
    name: @project.artifactId@
    build:
      version: @project.version@
      timestamp: @maven.build.timestamp@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 7190000
      minimum-idle: 2
      maximum-pool-size: 50
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

    spring:
      rabbitmq:
        listener:
          simple:
            default-requeue-rejected=false:

  flyway:
    baseline-description: baseline
    baseline-version: 0.1.0
    baseline-on-migrate: true
    out-of-order: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  #rabbitmq:
   # host: localhost
   # port: 5762
   # username: guest
  #  password: guest
   # template:
   #   exchange: rabbit.topic
    #  routing-key: rabbit.routingkeye
    #  default-receive-queue: rabbit.queue

logging:
  level.root: info
  level.com.sredasolutions.mobiliuz.rest.config.HttpTraceConfig: ${LOG_LEVEL_HTTP:info}

app:
  jwt:
    secrets:
      HS256: "1inf5hETo8ROAknhOwnNZuvhgts2LFNtsD7vJTwFo+s="
      HS384: "k2rPaImZTWdnmx92m+c+Z6xEMjmA10f79mx6a+Syesay21XnnUxXLgUvlYO4h0dP"
      HS512: "SfRmmYLzLLEHNkiNUvluPZIssmB2LssnhKj0a3Mr5v4CHoLk7MnovLhJ7we1CFA5zYV7eQPDsfPqWYcX9ywlnw=="
    selectedAlg: "HS256"
    ttl: 2592000000 # 30 * 24 * 3600 * 1000 # 30 days in millis
  fcm:
    configuration-file: "fcm-acc.json"

egts-websocket:
  url: ${WS_URL}
  topic: ${WS_TOPIC:all_car_states}
  notification-topic: ${WS_NOTIFICATION_TOPIC:all_events}
  device-command-topic: ${WS_DEVICE_COMMAND_TOPIC:all_device_commands}

 # egts-rabbitmq:
  #url: ${RB_URL}
  #topic: ${RB_TOPIC:all_car_states}
 # notification-topic: ${RB_NOTIFICATION_TOPIC:all_events}
  #device-command-topic: ${RB_DEVICE_COMMAND_TOPIC:all_device_commands}
trips:
  min-speed: 8.33   # 30 км/ч
